name: backend
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  firedart: ^0.9.8
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  meta: ^1.16.0

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
